name: Simple pipeline to build firmware and save generated image
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Build Project
        uses: docker://lagerdata/devenv-cortexm
        with:
          entrypoint: /usr/bin/make


      - name: Save hex image
        uses: actions/upload-artifact@v2
        with:
          name: blinky_hex_image
          path: _build/nrf52840_xxaa.hex